repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.9.1" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
